server:
  port: 8088
spring:
  application:
    name: /jenkins-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redis_learn?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.jenkins.demo.Mapper: debug
  config: classpath:logback-spring.xml
